### ISSUE TITLE
Undefined namespace

### ISSUE THREAD

**Issue by JcDenton86** [whiskyechobravo/views_oai_pmh#1]
Hi,
I am using this module in order to provide a OAI-PMH target using LOM. I created the view and i am getting the xml response at this URL: http://www.digiskills-project.eu/?q=oairequest&verb=ListRecords&metadataPrefix=oai_lom

If i hit the url above the xml works, but if i navigate to a page of the platform i get the warning below:

Warning: DOMXPath::query(): Undefined namespace prefix in views_oai_pmh_plugin_style->append_record_metadata() (line 421 of C:...\sites\all\modules\views_oai_pmh\plugins\views_oai_pmh_plugin_style.inc).

EDIT:
In order to reproduce, I found out that this happens only when you hit directly the oai-pmh url and after it finishing loading the xml, then visit the platform url from the same browser. And it's happening only the 1st time you visit the platform url. That means that other users will not see the warning, unless they hit firstly the oai-pmh url in their browsers.

Can you provide any help on that?

Thank you

**Comment by davidlesieur** [comment]
Actually, I'm also getting this warning but had not noticed it until you mentioned it. 

It looks like I have missed calling registerNamespace() on the DOMXPath object before querying it, in method views_oai_pmh_plugin_style::append_record_metadata(), so this is really a bug in the code. The list of namespaces will probably have to be retrieved from the views_oai_pmh_format object, and then registered on the DOMXPath object. I'll try to work on this real soon.

**Comment by JcDenton86** [comment]
Actually registering namespace fixed the warning. To test it out i just wrote this line of code right before querying :
$xpath->registerNamespace('oai_lom', 'http://ltsc.ieee.org/xsd/LOM');

This applies for my situation where i use LOM.

**Comment by davidlesieur** [comment]
Thanks for the test! That confirms the cause of the problem.
